### ISSUE TITLE
57 page of the book ( chapter 4 )

### ISSUE THREAD

**Issue by bronybro** [zhashkevych/go-basics#3]
![изображение](https://user-images.githubusercontent.com/54715893/115089982-47f3e900-9f1c-11eb-9257-318018a02b1a.png)
fix this little mistake if you are going to release the next edition of the book.

**Comment by zhashkevych** [comment]
Thank you! I probably will.

---
С уважением,
Максим
YouTube <https://www.youtube.com/c/MaksimZhashkevych> | LinkedIn
<https://www.linkedin.com/in/zhashkevych/> | Github
<https://github.com/zhashkevych>

zhashkevych.com
